### PR TITLE
bump phpdotenv version to v5

### PR DESCRIPTION
**Pull request by yongkyali**
#2

### CODE REVIEW

**Comment by irazasyed** [comment]
Please bump it to `^5.2` and remove the composer lock file.

**Comment by yongkyali** [comment]
Here's the change as advised. Please let me know if there's any other change necessary. Thanks!

**Comment by irazasyed** [comment]
Please remove the `composer.lock` file.

**Comment by yongkyali** [comment]
I've removed `composer.lock` file in the lastest commit. Please check it again. Thanks!

**Comment by irazasyed** [comment]
Thanks 👍

**Pull request merged**
